apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.name }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: victorZKov/${{ values.name }}
    backstage.io/techdocs-ref: dir:.
  tags:
    - dotnet
    - api
spec:
  type: service
  lifecycle: production
  owner: ${{ values.owner }}
  system: victorz-cloud
